/**
 * 1. 문제정보
 *  - 제목 : 오프라인/온라인 판매 데이터 통합하기
 *  - 링크 : https://school.programmers.co.kr/learn/courses/30/lessons/131537
 *  2. 풀이핵심
 *  - UNION
 * 3. 풀이후기
 *  - 합집합을 표현하는 UNION을 활용한다.
 */
SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM (
    SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
    FROM ONLINE_SALE
    UNION ALL
    SELECT SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
    FROM OFFLINE_SALE
) AS R
WHERE SALES_DATE BETWEEN "2022-03-01" AND "2022-03-31"
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID